apiVersion: v2
type: application
kubeVersion: ">=1.20.0"
# This is the chart version. This version number should be incremented each time you make changes
# to the chart and its templates, including the app version.
# Versions are expected to follow Semantic Versioning (https://semver.org/)
version: 0.9.1
# This is the version number of the application being deployed. This version number should be
# incremented each time you make changes to the application. Versions are not expected to
# follow Semantic Versioning. They should reflect the version the application is using.
# It is recommended to use it with quotes.
appVersion: "0.9.1"
name: spin-containerd-shim-installer
description: A Helm chart for installing the containerd shim for Spin on Kubernetes
home: https://github.com/fermyon/spin-containerd-shim-installer
icon: https://raw.githubusercontent.com/fermyon/spin-containerd-shim-installer/main/icon.svg
keywords:
  - fermyon
  - spin
  - containerd
  - wasm
  - wasi
  - webassembly
sources:
  - "https://github.com/fermyon/spin-containerd-shim-installer"
  - "https://github.com/deislabs/containerd-wasm-shims"
maintainers:
  - name: Justin Pflueger
    email: justin.pflueger@fermyon.com
