name: Installer Image CI

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version of the docker image and embedded shim to build'
        type: string
        required: true
        default: '0.5.1'
  workflow_call:
    inputs:
      version:
        description: 'Version of the docker image and embedded shim to build'
        type: string
        required: true

permissions:
  contents: read
  packages: write

jobs:
  build-and-push:
    name: "Build and Push v${{ github.event.inputs.version }}"
    runs-on: ubuntu-latest
    strategy:
      matrix:
        platform: [linux/amd64, linux/arm64]
    steps:
      - uses: actions/checkout@v3
      - uses: docker/setup-qemu-action@v2
      - uses: docker/setup-buildx-action@v2
      - uses: azure/setup-helm@v3

      - name: Login to ghcr
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Docker - Metadata
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: |
            ghcr.io/${{ github.repository }}
          tags: |
            ${{ github.event.inputs.version }}-{{ sha }}
            ${{ github.event.inputs.version }}

      - name: Docker - Build and Push
        uses: docker/build-push-action@v4
        with:
          context: ./image
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          build-args: |
            SHIM_VERSION=${{ github.event.inputs.version }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: clear local credentials
        if: always()
        run: |
          rm -f ${HOME}/.docker/config.json
          rm -f ${HOME}/.config/helm/registry/config.json
