name: Test

on:
  push:
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+"

permissions:
  contents: read
  packages: write

jobs:
  test:
    name: "Build and Push ${{ github.ref_name }}"
    runs-on: ubuntu-latest
    strategy:
      matrix:
        platform: [linux/amd64, linux/arm64]
    steps:
      - uses: actions/checkout@v3

      - id: variables
        run: |
          echo "version=${INPUT#v}" >> $GITHUB_OUTPUT
        env:
          REF_NAME: "${{ github.ref_name }}"

      - run: |
          echo "${{ steps.variables.outputs.version }}"

          echo "which yq"
          which yq
